[tool.poetry]
name = "elk-bledom"
version = "0.1.0"
description = ""
authors = ["Hacksore"]

[tool.poetry.dependencies]
python = "^3.8"
bluepy = "^1.3.0"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
